/**
 * Regenerates `src/fontData.ts` from the `geist` package's variable fonts.
 * Run after bumping `geist`:  node audio/embed-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const b64 = (p) => fs.readFileSync(path.join(root, p)).toString('base64');

const sans = b64('node_modules/geist/dist/fonts/geist-sans/Geist-Variable.woff2');
const mono = b64('node_modules/geist/dist/fonts/geist-mono/GeistMono-Variable.woff2');

const header = `/**
 * Geist and Geist Mono, base64-inlined from the \`geist\` npm package.
 *
 * Generated by \`node audio/embed-fonts.mjs\` — do not hand-edit.
 *
 * Why inlined rather than fetched from public/: a per-frame render kept stalling
 * on the woff2 request (a delayRender for the font timed out at frame 563), and a
 * font that resolves on 2000 frames but not the 2001st is a broken render. A data
 * URI has nothing to stall on.
 */

`;

fs.writeFileSync(
  path.join(root, 'src/fontData.ts'),
  `${header}export const GEIST_SANS_WOFF2 = '${sans}';\n\nexport const GEIST_MONO_WOFF2 = '${mono}';\n`,
);
console.log('wrote src/fontData.ts');

// The reel's closing line (owner, round 6: "it needs a different font"):
// Instrument Serif (OFL, @fontsource/instrument-serif), inlined the same way
// and kept in its own file so the film's fontData.ts is untouched.
const serif = b64('node_modules/@fontsource/instrument-serif/files/instrument-serif-latin-400-normal.woff2');
fs.writeFileSync(
  path.join(root, 'src/serifFontData.ts'),
  `/** Instrument Serif 400, base64-inlined. Generated by \`node audio/embed-fonts.mjs\`: do not hand-edit. */\nexport const INSTRUMENT_SERIF_WOFF2 = '${serif}';\n`,
);
console.log('wrote src/serifFontData.ts');
