"""The two finalist treatments, retuned for a MASS letterform.

Both earlier palettes were built around a monoline mark where the glow was the
letter. Apex is a solid form with cut terminals and a real point, so both
treatments here light it from outside instead of making it emit: crisp edge
bands generated by masking the shape against an offset copy of itself, and only
enough atmosphere to seat it on the tile.
"""
from marks import emit

EDGE_MASKS = """
    <!-- a band hugging the top edge: the shape minus itself pushed down -->
    <mask id="topEdge">
      {mark_w}
      {mark_b_down}
    </mask>
    <!-- and the mirror of it along the bottom -->
    <mask id="botEdge">
      {mark_w}
      {mark_b_up}
    </mask>
    <mask id="body">{mark_w}</mask>"""


def _masks(mk, down=8, up=10):
    return EDGE_MASKS.format(
        mark_w=emit(mk, "#FFFFFF"),
        mark_b_down=emit(mk, "#000000", f'transform="translate(0,{down})"'),
        mark_b_up=emit(mk, "#000000", f'transform="translate(0,-{up})"'),
    )


def lumen_edge(mk):
    """LUMEN, retuned. The wide 34px bloom is gone — it was rounding off the
    apex cuts and the vertex point. What replaces it: a tight contact glow that
    seats the mark on the tile, and edge bands that describe the form."""
    return f"""<svg width="1024" height="1024" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <radialGradient id="bg" cx="50%" cy="36%" r="84%">
      <stop offset="0%"   stop-color="#282833"/>
      <stop offset="42%"  stop-color="#16161D"/>
      <stop offset="100%" stop-color="#07070A"/>
    </radialGradient>
    <radialGradient id="vign" cx="50%" cy="50%" r="70%">
      <stop offset="0%"   stop-color="#000000" stop-opacity="0"/>
      <stop offset="66%"  stop-color="#000000" stop-opacity="0"/>
      <stop offset="100%" stop-color="#000000" stop-opacity="0.60"/>
    </radialGradient>
    <radialGradient id="aura" gradientUnits="userSpaceOnUse" cx="512" cy="500" r="400">
      <stop offset="0%"   stop-color="#FFFFFF" stop-opacity="0.11"/>
      <stop offset="46%"  stop-color="#CBD2E2" stop-opacity="0.04"/>
      <stop offset="100%" stop-color="#CBD2E2" stop-opacity="0"/>
    </radialGradient>
    <!-- a lit solid, not an emitter: brightest along the top, falling away -->
    <linearGradient id="body" gradientUnits="userSpaceOnUse" x1="0" y1="286" x2="0" y2="742">
      <stop offset="0%"   stop-color="#FFFFFF"/>
      <stop offset="42%"  stop-color="#F2F5FA"/>
      <stop offset="100%" stop-color="#CBD2E0"/>
    </linearGradient>
    <filter id="contact" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="9"/></filter>
    <filter id="edgeSoft" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="2"/></filter>
{_masks(mk)}
  </defs>

  <rect width="1024" height="1024" fill="url(#bg)"/>
  <rect width="1024" height="1024" fill="url(#vign)"/>
  <circle cx="512" cy="500" r="400" fill="url(#aura)"/>

  <!-- tight contact glow, under the crisp shape so the corners stay corners -->
  <g filter="url(#contact)" opacity="0.42">
    {emit(mk, "#B8C0D2")}
  </g>

  {emit(mk, "url(#body)")}

  <g filter="url(#edgeSoft)">
    <rect width="1024" height="1024" fill="#FFFFFF" mask="url(#topEdge)" opacity="0.85"/>
    <rect width="1024" height="1024" fill="#7A8296" mask="url(#botEdge)" opacity="0.26"/>
  </g>
</svg>
"""


def monolith_tuned(mk):
    """MONOLITH, tuned for Apex: the lip and the banked shadow are tightened so
    the cut edges stay hard, and the stone is calmed so the letter carries the
    contrast on its own."""
    return f"""<svg width="1024" height="1024" viewBox="0 0 1024 1024" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="stone" x1="10%" y1="0%" x2="28%" y2="100%">
      <stop offset="0%"   stop-color="#FCFBF8"/>
      <stop offset="48%"  stop-color="#F2F0EA"/>
      <stop offset="100%" stop-color="#DEDBD2"/>
    </linearGradient>
    <filter id="grain" x="0%" y="0%" width="100%" height="100%">
      <feTurbulence type="fractalNoise" baseFrequency="0.9" numOctaves="4" seed="3"/>
      <feColorMatrix type="saturate" values="0"/>
      <feComponentTransfer><feFuncA type="linear" slope="0.055"/></feComponentTransfer>
    </filter>
    <linearGradient id="cut" gradientUnits="userSpaceOnUse" x1="0" y1="286" x2="0" y2="742">
      <stop offset="0%"   stop-color="#212127"/>
      <stop offset="55%"  stop-color="#2B2B33"/>
      <stop offset="100%" stop-color="#40404B"/>
    </linearGradient>
    <radialGradient id="lift" cx="42%" cy="30%" r="78%">
      <stop offset="0%"   stop-color="#FFFFFF" stop-opacity="0.34"/>
      <stop offset="62%"  stop-color="#FFFFFF" stop-opacity="0"/>
    </radialGradient>
    <radialGradient id="vign4" cx="50%" cy="44%" r="74%">
      <stop offset="0%"   stop-color="#75705F" stop-opacity="0"/>
      <stop offset="58%"  stop-color="#75705F" stop-opacity="0"/>
      <stop offset="100%" stop-color="#75705F" stop-opacity="0.16"/>
    </radialGradient>
    <filter id="ao" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="11"/></filter>
    <filter id="edgeSoft" x="-40%" y="-40%" width="180%" height="180%">
      <feGaussianBlur stdDeviation="2.4"/></filter>
{_masks(mk, down=9, up=11)}
  </defs>

  <rect width="1024" height="1024" fill="url(#stone)"/>
  <rect width="1024" height="1024" fill="url(#lift)"/>
  <rect width="1024" height="1024" filter="url(#grain)" fill="#8B877C" opacity="0.28"/>

  <!-- the stone's lower lip, raised into the light just past the cut -->
  <g filter="url(#edgeSoft)" opacity="0.8">
    {emit(mk, "#FFFFFF", 'transform="translate(0,9)"')}
  </g>
  <g filter="url(#ao)" opacity="0.12">
    {emit(mk, "#5C5849", 'transform="translate(0,4)"')}
  </g>

  {emit(mk, "url(#cut)")}

  <!-- shadow banked against the upper wall, light grazing the lower one -->
  <g filter="url(#edgeSoft)">
    <rect width="1024" height="1024" fill="#111116" mask="url(#topEdge)" opacity="0.72"/>
    <rect width="1024" height="1024" fill="#8E8B9C" mask="url(#botEdge)" opacity="0.34"/>
  </g>
</svg>
"""
