import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Machina AI",
  description: "The terms that govern your use of Machina AI.",
};

/**
 * Public, static terms of service (no auth, no client hooks — prerenders under
 * `output: export`). Linked from App Store Connect and in-app Settings.
 */
export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-6 py-16">
      <Link href="/" className="text-sm text-text-secondary hover:text-text transition-colors">
        &larr; Machina AI
      </Link>

      <h1 className="mt-6 text-3xl font-semibold tracking-tight text-text">
        Terms of Service
      </h1>
      <p className="mt-2 text-sm text-text-muted">Last updated: July 20, 2026</p>

      <p className="mt-6 leading-relaxed text-text-secondary">
        These terms govern your use of Machina AI (&ldquo;Machina&rdquo;, the
        &ldquo;Service&rdquo;) — the iOS app, the web app, and the capture surfaces they connect to.
        By creating an account or using the Service you agree to them. If you do not agree, do not
        use the Service.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">1. What Machina is</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        Machina is a personal knowledge base. You save links, text, and images from the iOS share
        sheet, in-app add, a browser extension, or the web app; Machina analyzes each
        save with AI to produce summaries, categories, tags, and connections; and you can search
        your saves or ask questions answered from them, with citations. Features include reminders,
        digests, weekly syntheses, and collections.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">2. Your account</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        You sign in with a Google or Apple account and are responsible for activity that happens
        under it. You must be at least 13 years old. One account is for one person&rsquo;s personal
        use. How we handle your data is described in the{" "}
        <a href="/privacy" className="text-accent hover:underline">Privacy Policy</a>.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">3. Your content</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        Everything you save remains yours — Machina claims no ownership of your content. You grant
        us only the limited license needed to operate the Service: to store your content, process it
        with the AI providers named in the Privacy Policy, and display it back to you. If you choose
        to publish a card or collection as a public share page, you also grant us the right to serve
        that snapshot publicly until you unpublish or delete it. You are responsible for what you
        save and share, including having the right to do so.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">4. Acceptable use</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">You agree not to:</p>
      <ul className="mt-4 list-disc space-y-2 pl-6 leading-relaxed text-text-secondary">
        <li>use the Service for anything unlawful, or save or publicly share content that is
          illegal, infringing, or harmful to others;</li>
        <li>probe, overload, or disrupt the Service, or attempt to access another person&rsquo;s
          workspace or non-public parts of the system;</li>
        <li>circumvent usage limits, automate bulk access, or resell the Service;</li>
        <li>misuse the AI features to generate or distribute abusive content.</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-text">5. AI output</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        Summaries, tags, connections, syntheses, and answers are generated by AI from the content
        you saved. They can be inaccurate, incomplete, or out of date, and they are not
        professional (legal, medical, financial, or other) advice. Verify anything important against
        the original source — that is why answers carry citations.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">6. Third-party content</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        Saved links point to content owned by third parties, and Machina&rsquo;s extracts of that
        content are for your personal reference. The original sites&rsquo; own terms and rights
        apply to their content.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">7. Availability and changes</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo;, without
        warranties of any kind, express or implied. We may add, change, or remove features, and we
        may suspend or discontinue the Service; if we discontinue it, we will give you a reasonable
        opportunity to delete or retrieve your content first.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">8. Limitation of liability</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        To the maximum extent permitted by law, Machina and its operator are not liable for
        indirect, incidental, special, consequential, or punitive damages, or for loss of data,
        profits, or goodwill, arising from your use of the Service. Our total liability for any
        claim is limited to the greater of the amount you paid us in the twelve months before the
        claim or US $50. Nothing in these terms excludes liability that cannot be excluded by law.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">9. Termination</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        You can stop using Machina and delete your account (Settings &rarr; Delete account) at any
        time; deletion permanently removes your data as described in the Privacy Policy. We may
        suspend or terminate accounts that violate these terms or put the Service or other users at
        risk, with notice where practical.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">10. Governing law</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        These terms are governed by the laws of the State of Israel, without regard to
        conflict-of-law rules, and any dispute arising from them or from the Service will be
        brought exclusively in the competent courts of Tel Aviv-Jaffa, Israel. If you use the
        Service as a consumer, this does not affect any mandatory consumer protections or venue
        rights granted by the law of the country you live in.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">11. Changes to these terms</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        If we change these terms, we will update the date at the top of this page and point out
        material changes in the app. Continuing to use the Service after a change takes effect means
        you accept the updated terms.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-text">12. Contact</h2>
      <p className="mt-4 leading-relaxed text-text-secondary">
        Questions about these terms:{" "}
        <a href="mailto:morhogeg@gmail.com" className="text-accent hover:underline">
          morhogeg@gmail.com
        </a>
      </p>

      <footer className="mt-14 border-t border-border-subtle pt-6 text-sm text-text-muted">
        <a href="/privacy" className="hover:text-text transition-colors">Privacy Policy</a>
        <span className="mx-2">&middot;</span>
        <Link href="/" className="hover:text-text transition-colors">Machina AI</Link>
      </footer>
    </main>
  );
}
